# oh-my-zsh
export ZSH=${HOME}/.oh-my-zsh
export TERM=xterm
export EDITOR=vim

plugins=(git ssh-agent zsh-256color)

ZSH_THEME=blinks
zstyle :omz:plugins:ssh-agent identities id_rsa_ghbb

source ${ZSH}/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
