# oh-my-zsh
export ZSH=${HOME}/.oh-my-zsh
export TERM=xterm
export EDITOR=vim

$(git clone https://github.com/chrissicool/zsh-256color ${ZSH}/plugins/zsh-256color 2> /dev/null)

plugins=(git ssh-agent zsh-256color)

ZSH_THEME=blinks
zstyle :omz:plugins:ssh-agent identities id_rsa

source ${ZSH}/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
