FROM mdotcarter/devenv

RUN sudo apt-get update --fix-missing && sudo apt-get install -y \
      build-essential \
      nodejs \
      wget

# rvm
RUN sudo gpg --batch --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

RUN curl -sSL https://get.rvm.io | sudo bash -s stable
RUN sudo usermod -a -G rvm ${USER}
RUN . /etc/profile.d/rvm.sh
