FROM mdotcarter/devenv

RUN sudo apt-get update --fix-missing && sudo apt-get install -y \
      build-essential \
      wget

# postgres 10 client
RUN sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
RUN sudo sh -c 'wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -'

RUN sudo apt-get update && sudo apt-get install -y \
      libpq-dev \
      postgresql-client-10

# openjdk-8
RUN sudo apt-get update --fix-missing && sudo apt-get install -y \
      openjdk-11-jdk
