FROM mdotcarter/devenv

# pyenv recommended build environment
#RUN sudo apt update && sudo apt install -y \
        #build-essential \
        #libssl-dev \
        #zlib1g-dev \
        #libbz2-dev \
        #libreadline-dev \
        #libsqlite3-dev \
        #curl \
        #llvm \
        #libncursesw5-dev \
        #xz-utils \
        #tk-dev \
        #libxml2-dev \
        #libxmlsec1-dev \
        #libffi-dev \
        #liblzma-dev \
        #libpq-dev \
        #python3-pip \
        #python3-venv

# Pyenv
#RUN curl https://pyenv.run | bash

# NVM
#RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
