FROM mdotcarter/devenv

# Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH ${HOME}/.cargo/bin:${PATH}

# Racer
RUN rustup component add rust-src
RUN rustup toolchain add nightly
RUN cargo +nightly install racer
