FROM mdotcarter/devenv

RUN sudo apt-get update --fix-missing && sudo apt-get install -y \
      build-essential \
      wget

# openjdk-8
RUN sudo apt-get update --fix-missing && sudo apt-get install -y \
      openjdk-11-jdk

ENV JAVA_HOME="$(dirname $(dirname $(realpath $(which javac))))"

# bazel
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
RUN sudo apt-get install curl
RUN curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

RUN sudo apt-get update --fix-missing && sudo apt-get install -y \
      bazel

# intellij
RUN (cd /tmp && curl http://download.jetbrains.com/idea/ideaIC-2019.2.3-no-jbr.tar.gz -LO)
RUN sudo tar -C /opt -xzf /tmp/ideaIC-2019.2.3-no-jbr.tar.gz

ENV PATH ${PATH}:/opt/idea-IC-192.6817.14/bin
